# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.LearningRateMonitor.html

learning_rate_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: 'epoch' # 'step' or 'epoch'
  log_momentum: False # whether to log the momentum
  log_weight_decay: False # whether to log the weight decay

 