_target_: src.models.components.dit3d.DiT3D

input_size: 32
patch_size: 2
in_channels: 4
hidden_size: 376 # 1152
depth: 12 #28
num_heads: 8  
mlp_ratio: 4
class_dropout_prob: 0.1
num_classes: 1000
learn_sigma: False 